# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pytube import YouTube
from pathlib import Path
import threading
import os


class Ui_VideoDownloader(object):
    def setupUi(self, VideoDownloader):
        VideoDownloader.setObjectName("VideoDownloader")
        VideoDownloader.resize(509, 625)
        VideoDownloader.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(VideoDownloader)
        self.centralwidget.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176, 255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184, 160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385 rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 3, 0, 1, 2)
        self.r2 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.r2.setFont(font)
        self.r2.setStyleSheet("")
        self.r2.setObjectName("r2")
        self.gridLayout_3.addWidget(self.r2, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.r4 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.r4.setFont(font)
        self.r4.setStyleSheet("")
        self.r4.setObjectName("r4")
        self.gridLayout_3.addWidget(self.r4, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Onyx")
        font.setPointSize(36)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(84, 31, 131);\n"
"background-color:transparent")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.r5 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.r5.setFont(font)
        self.r5.setStyleSheet("")
        self.r5.setObjectName("r5")
        self.gridLayout_3.addWidget(self.r5, 6, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.r6 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.r6.setFont(font)
        self.r6.setStyleSheet("")
        self.r6.setObjectName("r6")
        self.gridLayout_3.addWidget(self.r6, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 7, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 2)
        self.r1 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.r1.setFont(font)
        self.r1.setStyleSheet("")
        self.r1.setObjectName("r1")
        self.gridLayout_3.addWidget(self.r1, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.downloadbtn = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.do())
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.downloadbtn.setFont(font)
        self.downloadbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.downloadbtn.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.119403 rgba(131, 0, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color:black;\n"
"padding:10px;\n"
"border:2px;\n"
"border-radius:20px;")
        self.downloadbtn.setObjectName("downloadbtn")
        # self.downloadbtn.clicked.connect(self.do())
        self.gridLayout_3.addWidget(self.downloadbtn, 8, 0, 1, 2, QtCore.Qt.AlignHCenter)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setStyleSheet("border:2px solid blue;\n"
"border-bottom-color:rgb(60, 255, 223);\n"
"border-top-color:transparent;\n"
"background:transparent;")
        self.lineEdit.setMaxLength(32780)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 2, 0, 1, 2)
        self.r3 = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(14)
        self.r3.setFont(font)
        self.r3.setStyleSheet("")
        self.r3.setObjectName("r3")
        self.gridLayout_3.addWidget(self.r3, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 10, 0, 1, 2)
        self.statuslbl = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.statuslbl.setFont(font)
        self.statuslbl.setText("")
        self.statuslbl.setObjectName("statuslbl")
        self.gridLayout_3.addWidget(self.statuslbl, 9, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        VideoDownloader.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VideoDownloader)
        self.statusbar.setObjectName("statusbar")
        VideoDownloader.setStatusBar(self.statusbar)

        self.retranslateUi(VideoDownloader)
        QtCore.QMetaObject.connectSlotsByName(VideoDownloader)

    def retranslateUi(self, VideoDownloader):
        _translate = QtCore.QCoreApplication.translate
        VideoDownloader.setWindowTitle(_translate("VideoDownloader", "MainWindow"))
        self.r2.setText(_translate("VideoDownloader", "240p(MP4)"))
        self.r4.setText(_translate("VideoDownloader", "480p(MP4)"))
        self.label.setText(_translate("VideoDownloader", "Video Downloader"))
        self.r5.setText(_translate("VideoDownloader", "720p(MP4)"))
        self.r6.setText(_translate("VideoDownloader", "1080p (HD)"))
        self.r1.setText(_translate("VideoDownloader", "144p(MP4)"))
        self.downloadbtn.setToolTip(_translate("VideoDownloader", "Download"))
        self.downloadbtn.setText(_translate("VideoDownloader", "Download"))
        self.r3.setText(_translate("VideoDownloader", "360p(MP4)"))

    def do(self):
        if self.r1.isChecked(): self._download('144p')
        if self.r2.isChecked(): self._download('240p')
        if self.r3.isChecked(): self._download('360p')
        if self.r4.isChecked(): self._download('480p')
        if self.r5.isChecked(): self._download('720p')
        if self.r6.isChecked(): self._download('1080p')

    def _download(self, pixel):
        threading.Thread(target=self.download_, args=[pixel]).start()

    def download_(self, pixel):
        url = str(self.lineEdit.text())
        yt = YouTube(url, use_oauth=True, allow_oauth_cache=True)
        try:
            self.downloadbtn.setText("Downloading")
            self.statuslbl.setText(f"Downloading {pixel} Video")
            video = yt.streams.filter(res=pixel).first()
            destination = str(Path.home()/"Downloads")
            out_file = video.download(output_path=destination)
            base, ext = os.path.splitext(out_file)
            new_file = base + '.mp4'
            os.rename(out_file, new_file)
            self.statuslbl.setText(f"Downloaded to:{destination}")
            self.downloadbtn.setText("Download")
        except Exception as e:
            print(str(e))
            self.statuslbl.setText("Error!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VideoDownloader = QtWidgets.QMainWindow()
    ui = Ui_VideoDownloader()
    ui.setupUi(VideoDownloader)
    VideoDownloader.show()
    sys.exit(app.exec_())
